"Emerald Config" = {}

#World Gen - Ore Generation Configuration
["Coal Config"]

	["Coal Config".Overworld]
		#Activate/Deactivate the Ore Gen in The Overworld [Default: true]
		generate_in_the_overworld = true
		#Baseline Y-Level [Default: 60]
		#Range: 0 ~ 256
		overworld_base = 60
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 60]
		#Range: 0 ~ 256
		overworld_spread = 60
		#Average Ores per Chunk [Default: 15]
		#Range: 0 ~ 64
		overworld_count = 15
		#Configure the ore Vein Size [Default: 17]
		#Range: 0 ~ 64
		overworld_size = 17
		#Use spread mechanic instead of random range [Default: true]
		overworld_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		overworld_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		overworld_biome_list_invert = false

	["Coal Config"."The Nether"]
		#Activate/Deactivate the Ore Gen in The Nether [Default: false]
		generate_in_the_nether = false
		#Baseline Y-Level [Default: 90]
		#Range: 0 ~ 128
		nether_base = 90
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 60]
		#Range: 0 ~ 128
		nether_spread = 60
		#Average Ores per Chunk [Default: 15]
		#Range: 0 ~ 64
		nether_count = 15
		#Ore Vein Size [Default: 17]
		#Range: 0 ~ 64
		nether_size = 17
		#Use spread mechanic instead of random range [Default: true]
		nether_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		nether_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		nether_biome_list_invert = false

	["Coal Config"."The End"]
		#Activate/Deactivate the Ore Gen in The End [Default: false]
		generate_in_the_end = false
		#Baseline Y-Level [Default: 80]
		#Range: 0 ~ 256
		end_base = 80
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 60]
		#Range: 0 ~ 256
		end_spread = 60
		#Average Ores per Chunk [Default: 15]
		#Range: 0 ~ 64
		end_count = 15
		#Ore Vein Size [Default: 17]
		#Range: 0 ~ 64
		end_size = 17
		#Use spread mechanic instead of random range [Default: true]
		end_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		end_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		end_biome_list_invert = false

["Iron Config"]

	["Iron Config".Overworld]
		#Activate/Deactivate the Ore Gen in The Overworld [Default: true]
		generate_in_the_overworld = true
		#Baseline Y-Level [Default: 32]
		#Range: 0 ~ 256
		overworld_base = 32
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 32]
		#Range: 0 ~ 256
		overworld_spread = 32
		#Average Ores per Chunk [Default: 17]
		#Range: 0 ~ 64
		overworld_count = 17
		#Configure the ore Vein Size [Default: 11]
		#Range: 0 ~ 64
		overworld_size = 11
		#Use spread mechanic instead of random range [Default: true]
		overworld_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		overworld_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		overworld_biome_list_invert = false

	["Iron Config"."The Nether"]
		#Activate/Deactivate the Ore Gen in The Nether [Default: false]
		generate_in_the_nether = false
		#Baseline Y-Level [Default: 62]
		#Range: 0 ~ 128
		nether_base = 62
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 32]
		#Range: 0 ~ 128
		nether_spread = 32
		#Average Ores per Chunk [Default: 17]
		#Range: 0 ~ 64
		nether_count = 17
		#Ore Vein Size [Default: 11]
		#Range: 0 ~ 64
		nether_size = 11
		#Use spread mechanic instead of random range [Default: true]
		nether_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		nether_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		nether_biome_list_invert = false

	["Iron Config"."The End"]
		#Activate/Deactivate the Ore Gen in The End [Default: false]
		generate_in_the_end = false
		#Baseline Y-Level [Default: 52]
		#Range: 0 ~ 256
		end_base = 52
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 32]
		#Range: 0 ~ 256
		end_spread = 32
		#Average Ores per Chunk [Default: 17]
		#Range: 0 ~ 64
		end_count = 17
		#Ore Vein Size [Default: 11]
		#Range: 0 ~ 64
		end_size = 11
		#Use spread mechanic instead of random range [Default: true]
		end_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		end_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		end_biome_list_invert = false

["Gold Config"]

	["Gold Config".Overworld]
		#Activate/Deactivate the Ore Gen in The Overworld [Default: true]
		generate_in_the_overworld = true
		#Baseline Y-Level [Default: 16]
		#Range: 0 ~ 256
		overworld_base = 16
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 16]
		#Range: 0 ~ 256
		overworld_spread = 16
		#Average Ores per Chunk [Default: 7]
		#Range: 0 ~ 64
		overworld_count = 7
		#Configure the ore Vein Size [Default: 8]
		#Range: 0 ~ 64
		overworld_size = 8
		#Use spread mechanic instead of random range [Default: true]
		overworld_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		overworld_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		overworld_biome_list_invert = false

	["Gold Config"."The Nether"]
		#Activate/Deactivate the Ore Gen in The Nether [Default: false]
		generate_in_the_nether = false
		#Baseline Y-Level [Default: 46]
		#Range: 0 ~ 128
		nether_base = 46
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 16]
		#Range: 0 ~ 128
		nether_spread = 16
		#Average Ores per Chunk [Default: 7]
		#Range: 0 ~ 64
		nether_count = 7
		#Ore Vein Size [Default: 8]
		#Range: 0 ~ 64
		nether_size = 8
		#Use spread mechanic instead of random range [Default: true]
		nether_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		nether_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		nether_biome_list_invert = false

	["Gold Config"."The End"]
		#Activate/Deactivate the Ore Gen in The End [Default: false]
		generate_in_the_end = false
		#Baseline Y-Level [Default: 36]
		#Range: 0 ~ 256
		end_base = 36
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 16]
		#Range: 0 ~ 256
		end_spread = 16
		#Average Ores per Chunk [Default: 7]
		#Range: 0 ~ 64
		end_count = 7
		#Ore Vein Size [Default: 8]
		#Range: 0 ~ 64
		end_size = 8
		#Use spread mechanic instead of random range [Default: true]
		end_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		end_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		end_biome_list_invert = false

["Diamond Config"]

	["Diamond Config".Overworld]
		#Activate/Deactivate the Ore Gen in The Overworld [Default: true]
		generate_in_the_overworld = true
		#Baseline Y-Level [Default: 8]
		#Range: 0 ~ 256
		overworld_base = 8
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 8]
		#Range: 0 ~ 256
		overworld_spread = 8
		#Average Ores per Chunk [Default: 3]
		#Range: 0 ~ 64
		overworld_count = 3
		#Configure the ore Vein Size [Default: 8]
		#Range: 0 ~ 64
		overworld_size = 8
		#Use spread mechanic instead of random range [Default: true]
		overworld_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		overworld_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		overworld_biome_list_invert = false

	["Diamond Config"."The Nether"]
		#Activate/Deactivate the Ore Gen in The Nether [Default: false]
		generate_in_the_nether = false
		#Baseline Y-Level [Default: 38]
		#Range: 0 ~ 128
		nether_base = 38
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 8]
		#Range: 0 ~ 128
		nether_spread = 8
		#Average Ores per Chunk [Default: 3]
		#Range: 0 ~ 64
		nether_count = 3
		#Ore Vein Size [Default: 8]
		#Range: 0 ~ 64
		nether_size = 8
		#Use spread mechanic instead of random range [Default: true]
		nether_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		nether_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		nether_biome_list_invert = false

	["Diamond Config"."The End"]
		#Activate/Deactivate the Ore Gen in The End [Default: false]
		generate_in_the_end = false
		#Baseline Y-Level [Default: 28]
		#Range: 0 ~ 256
		end_base = 28
		#Spread Amount (# of Y-Levels above and below the Baseline) [Default: 8]
		#Range: 0 ~ 256
		end_spread = 8
		#Average Ores per Chunk [Default: 3]
		#Range: 0 ~ 64
		end_count = 3
		#Ore Vein Size [Default: 8]
		#Range: 0 ~ 64
		end_size = 8
		#Use spread mechanic instead of random range [Default: true]
		end_use_spread = true
		#List of biome IDs in which the ore is not allowed to generate.
		#To blacklist all biomes from a single mod, use 'modid:*'
		end_biome_blacklist = []
		#Invert Blacklist to Whitelist [Default: false]
		end_biome_list_invert = false

